### PR TITLE
use 1em as default size instead of 24

### PR DESCRIPTION
**Pull request by Prinzhorn**

### CODE REVIEW

**Comment by Prinzhorn** [comment]
The material design icons actually have a recommended size of 24. I think font awesome looks best at 14px (or 16?).

So what I'm saying maybe we can use the recommended size (where the icons look crisp) for each set instead of the same default for all? What do you think?

**Comment by gorangajic** [comment]
not sure why they have set size fixed, anyway I think that your initial idea of setting size to 1em is great and we should go with it

**Comment by gorangajic** [comment]
I have checked how iconmoon.io generate svg inline icons and they provide default styling  
```css
.icon {
  display: inline-block;
  width: 1em;
  height: 1em;
  fill: currentColor;
}
```
so we should then add only `display: inline-block` and we are fine :smile:

**Comment by Prinzhorn** [comment]
Sorry for not replying. I agree with what you said.

**Pull request merged**
